### ISSUE TITLE
AttributeError when using aiohttp

### ISSUE THREAD

**Issue by haael** [beeware/gbulb#116]
### Describe the bug

When doing a GET request from aiohttp, console shows AttributeError. The error doesn't happen when using aiohttp outside of gbulb.

### Steps to reproduce

```
import aiohttp
def main(url):
    client = aiohttp.ClientSession()
    async with client.get(url) as response:
        response.raise_for_status()
        print(await response.read())
    await client.close()
```

### Expected behavior

Success.

### Environment

Ubuntu, Python 3.11

### Logs

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/gbulb/transports.py", line 177, in _loop_reading
    self._submit_read_data(data)
  File "/usr/local/lib/python3.11/dist-packages/gbulb/transports.py", line 127, in _submit_read_data
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'

```

**Comment by freakboy3742** [comment]
Thanks for the report - unfortunately, I can't reproduce this failure.

Firstly, because it looks like you've trimmed a little *too* much from your reproduction example - it can't work as written because main isn't declared `async`. I had to modify it to read:

```
import asyncio
import aiohttp

async def main(url):
    client = aiohttp.ClientSession()
    async with client.get(url) as response:
        response.raise_for_status()
        print(await response.read())
    await client.close()

if __name__ == "__main__":
    asyncio.run(main("https://www.wikipedia.org/"))
```

Even then, on Python 3.11 on Fedora 38, it works fine for me on multiple runs.

The one detail you didn't include in your bug report was the version of gbulb you are using; is it possible you're running an older gbulb version that didn't have Python 3.11 support?

**Comment by freakboy3742** [comment]
Note to self: don't review tickets before the coffee kicks in. I just realised I didn't test this against gbulb - I was just running it a virtual environment that had gbulb installed. 

Apologies for the confusion; I'll take a second look.

**Comment by freakboy3742** [comment]
I can now confirm I see this, but only on Python 3.11.

The test case is:
```
import asyncio
import aiohttp
import gbulb

async def main(url):
    client = aiohttp.ClientSession()
    async with client.get(url) as response:
        response.raise_for_status()
        print(await response.read())
    await client.close()

if __name__ == "__main__":
    gbulb.install()
    asyncio.run(main("https://www.wikipedia.org/"))
```

**Comment by odahoda** [comment]
Just ran into the same issue here (downgrading to python3.10 does indeed fix it).

To add a few more details: Looks like gbulb does not know how to deal with BufferedProtocol, which were added in 3.7, but it doesn't look like there were used in python's stdlib until 3.11, when SSLProtocol became a BufferedProtocol (https://github.com/python/cpython/commit/13c10bfb777483c7b02877aab029345a056b809c).

...ok, couldn't resist. It's really ugly, but it seems to work: https://github.com/odahoda/gbulb/commit/06c71af89f294279d9da8a185988d07d2754aaa0

**Comment by freakboy3742** [comment]
Thanks for that debugging - that means #58 and #60 are likely related. It would be worth checking if #60 fixes this problem - if it does, then that increases the impetus to finish the work needed to land that patch.

**Comment by odahoda** [comment]
The PR #60 does indeed look like the proper fix, though I can't test it easily, because the branch is outdated and missing other py3.11 related fixes...

**Comment by bitstuffing** [comment]
So... I'm interesting in this bug, how can I help you testing this issue? I'm in this situation with a simple WeSocket connection, but... reading this conversation I think we can check a "patch". 

Anyway, I have currently in my project this problem, so "I'm able to reproduce this issue".

**Comment by freakboy3742** [comment]
The testing strategy is to set up an environment and install the code from the PR branch, then see if it resolves the issue. 

The follow-up problem is that the neither the current codebase or the PR contains any tests that demonstrates the problem that has been reported. We need to add a test case that exercises the problematic code.

**Comment by bitstuffing** [comment]
> The testing strategy is to set up an environment and install the code from the PR branch, then see if it resolves the issue.
> 
> The follow-up problem is that the neither the current codebase or the PR contains any tests that demonstrates the problem that has been reported. We need to add a test case that exercises the problematic code.

But... I see that this PR should be tested 2 years before, it's not simple, there are a lot of incompatibilities with the current version. 

It needs more work than a simple checkout to be checked.

I see the error, and apparently, the author make a good work because apparently, creates the protocol.

Anyway, 2 years before... it's not a simple python version upgrade of our system, this error is happening too much time before.

About the tests... I understand that your tests are not failing, and I see why. In my project, I have added and launched a bug.py with the code and a `briefcase dev --test`, and with that it's working. Why? because this error is related with gbulb and GTK, so this error just happens when you build a GUI and not from console.

**Comment by bitstuffing** [comment]
I have applied a "merge" manually with the PR, and, at least for me, didn't solve the situation. So... need more work to be solved :'(
